import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AuthProvider } from "./provider/AuthProvider";
// import { ServiceCategoryProvider } from "./provider/ServiceCategoryProvider";
import { QueryClientProvider } from "./provider/QueryCientProvider";
import { GoogleOAuthProvider } from "@react-oauth/google"; // ✅ Add this

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <QueryClientProvider>
          <GoogleOAuthProvider
            clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
          >
            <AuthProvider>
              <ToastContainer position="top-right" autoClose={3000} />
              {children}
            </AuthProvider>
          </GoogleOAuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
