import { Request, Response } from "express";
import prisma from "../../prismaClient";

export const createPetPost = async (req: Request, res: Response) => {
  const {
    petName,
    address,
    about,
    image,
    phoneNumber,
    age,
    price,
    purpose,
    petCategoryId,
    size,
    gender,
    breed,
    video,
  } = req.body;

  const userId = Number(req.params.id);
  const updatedNumber = Number(phoneNumber);
  const updatedAge = Number(age);
  const updatedPrice = Number(price);
  try {
    const newPetPost = await prisma.petPost.create({
      data: {
        size: size,
        gender: gender,
        breed: breed,
        petName: petName,
        address: address,
        about: about,
        image: image,
        phoneNumber: updatedNumber,
        age: updatedAge,
        price: updatedPrice,
        purpose: purpose,
        petCategoryId: petCategoryId,
        userId: userId,
        video: video,
      },
      // data: [
      //   {
      //     size: "SMALL",
      //     gender: "MALE",
      //     breed: "Siamese",
      //     petName: "Mocha",
      //     address: "102 Purr St, Portland, OR",
      //     about: "Talkative and loving. Follows you everywhere.",
      //     image: "https://res.cloudinary.com/demo/image/upload/cat2.jpg",
      //     phoneNumber: 43276509,
      //     age: 2,
      //     price: 0,
      //     purpose: "ADOPT",
      //     petCategoryId: 2,
      //     userId: 3,
      //     video: "https://res.cloudinary.com/demo/video/upload/cat2.mp4",
      //   },
      //   {
      //     size: "SMALL",
      //     gender: "FEMALE",
      //     breed: "Cockatiel",
      //     petName: "Peachy",
      //     address: "15 Feather Rd, Orlando, FL",
      //     about: "Whistles tunes and loves attention.",
      //     image: "https://res.cloudinary.com/demo/image/upload/bird2.jpg",
      //     phoneNumber: 54387610,
      //     age: 8,
      //     price: 60,
      //     purpose: "SALE",
      //     petCategoryId: 3,
      //     userId: 2,
      //     video: "https://res.cloudinary.com/demo/video/upload/bird2.mp4",
      //   },
      //   {
      //     size: "SMALL",
      //     gender: "MALE",
      //     breed: "Mini Lop",
      //     petName: "Floppy",
      //     address: "62 Carrot Blvd, Boise, ID",
      //     about: "Loves to hop and cuddle. Gentle nature.",
      //     image: "https://res.cloudinary.com/demo/image/upload/rabbit2.jpg",
      //     phoneNumber: 65498721,
      //     age: 9,
      //     price: 45,
      //     purpose: "ADOPT",
      //     petCategoryId: 4,
      //     userId: 4,
      //     video: "https://res.cloudinary.com/demo/video/upload/rabbit2.mp4",
      //   },
      //   {
      //     size: "SMALL",
      //     gender: "FEMALE",
      //     breed: "Goldfish",
      //     petName: "Bubbles",
      //     address: "77 Riverbank Dr, Sacramento, CA",
      //     about: "Peaceful and colorful. Great for kids.",
      //     image: "https://res.cloudinary.com/demo/image/upload/fish2.jpg",
      //     phoneNumber: 760983214,
      //     age: 0.4,
      //     price: 10,
      //     purpose: "SALE",
      //     petCategoryId: 5,
      //     userId: 5,
      //     video: "https://res.cloudinary.com/demo/video/upload/fish2.mp4",
      //   },
      //   {
      //     size: "MIDDLE",
      //     gender: "MALE",
      //     breed: "Leopard Gecko",
      //     petName: "Leo",
      //     address: "8 Gecko St, Las Vegas, NV",
      //     about: "Nocturnal and loves warmth. Easy to feed.",
      //     image: "https://res.cloudinary.com/demo/image/upload/reptile2.jpg",
      //     phoneNumber: 876104325,
      //     age: 1,
      //     price: 80,
      //     purpose: "ADOPT",
      //     petCategoryId: 6,
      //     userId: 6,
      //     video: "https://res.cloudinary.com/demo/video/upload/reptile2.mp4",
      //   },
      //   {
      //     size: "SMALL",
      //     gender: "FEMALE",
      //     breed: "Dwarf Hamster",
      //     petName: "Pixie",
      //     address: "42 Acorn Ln, Salt Lake City, UT",
      //     about: "Fast and fun to watch. Low maintenance.",
      //     image: "https://res.cloudinary.com/demo/image/upload/hamster2.jpg",
      //     phoneNumber: 98732154,
      //     age: 3,
      //     price: 20,
      //     purpose: "SALE",
      //     petCategoryId: 7,
      //     userId: 7,
      //     video: "https://res.cloudinary.com/demo/video/upload/hamster2.mp4",
      //   },
      //   {
      //     size: "BIG",
      //     gender: "MALE",
      //     breed: "Clydesdale",
      //     petName: "Thunder",
      //     address: "Horse Hill Farm, Montana",
      //     about: "Strong workhorse. Great for pulling and show.",
      //     image: "https://res.cloudinary.com/demo/image/upload/horse2.jpg",
      //     phoneNumber: 98326547,
      //     age: 5,
      //     price: 300,
      //     purpose: "SALE",
      //     petCategoryId: 8,
      //     userId: 8,
      //     video: "https://res.cloudinary.com/demo/video/upload/horse2.mp4",
      //   },
      //   {
      //     size: "SMALL",
      //     gender: "FEMALE",
      //     breed: "Black-Footed Ferret",
      //     petName: "Zippy",
      //     address: "27 Burrow Dr, Minneapolis, MN",
      //     about: "Energetic explorer. Needs a lot of stimulation.",
      //     image: "https://res.cloudinary.com/demo/image/upload/ferret2.jpg",
      //     phoneNumber: 10954365,
      //     age: 1,
      //     price: 95,
      //     purpose: "ADOPT",
      //     petCategoryId: 9,
      //     userId: 9,
      //     video: "https://res.cloudinary.com/demo/video/upload/ferret2.mp4",
      //   },
      //   {
      //     size: "SMALL",
      //     gender: "MALE",
      //     breed: "Box Turtle",
      //     petName: "Tank",
      //     address: "33 Shellhouse Rd, Raleigh, NC",
      //     about: "Slow and steady. Can live for decades.",
      //     image: "https://res.cloudinary.com/demo/image/upload/turtle2.jpg",
      //     phoneNumber: 21065487,
      //     age: 6,
      //     price: 50,
      //     purpose: "SALE",
      //     petCategoryId: 10,
      //     userId: 1,
      //     video: "https://res.cloudinary.com/demo/video/upload/turtle2.mp4",
      //   },
      // ],
    });

    res.status(201).json({ success: true, data: newPetPost });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: true, message: "Internal server error" });
  }
};
